version: "3.8"

services:
  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=root
      - MARIADB_PASSWORD=
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_net

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    # Optional volume if you want to see/edit the Laravel code on your host:
    volumes:
      - ../backend:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app_net

  apache:
    build: ./apache
    container_name: apache
    # Because host port 80 might be in use, bind to 8080:80 or your choice
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    networks:
      - app_net
    volumes:
    - ../backend:/var/www/html

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"  # If you want to access Vite dev server from outside
    # Optional volume if you want to see/edit the Vue code on your host:
    volumes:
      - ../frontend:/app/frontend
    networks:
      - app_net

volumes:
  mariadb_data:
    driver: local

networks:
  app_net:
    driver: bridge
