name: Lint Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/lint-frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/lint-frontend.yml'

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "No Node project; skipping install."
          fi
      - name: Run ESLint
        run: |
          if [ -f package.json ]; then
            npm run lint
          else
            echo "No Node project; skipping lint."
          fi
