name: Test Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "No Node project; skipping install."
          fi
      - name: Run unit tests
        run: |
          if [ -f package.json ]; then
            npm test
          else
            echo "No Node project; skipping tests."
          fi
